<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class WP_AdServer_Fields {

	public static function init() {
		add_action( 'init', array( __CLASS__, 'register_fields' ) );
	}

	public static function register_fields() {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group( array(
			'key'      => 'group_wp_ad_details',
			'title'    => 'Ad Details',
			'fields'   => array(
				array(
					'key'           => 'field_wp_ad_active',
					'label'         => 'Active',
					'name'          => 'wp_ad_active',
					'type'          => 'true_false',
					'default_value' => 1,
					'ui'            => 1,
					'ui_on_text'    => 'Active',
					'ui_off_text'   => 'Inactive',
				),
				array(
					'key'           => 'field_wp_ad_type',
					'label'         => 'Ad Type',
					'name'          => 'wp_ad_type',
					'type'          => 'select',
					'choices'       => array(
						'image' => 'Image',
						'html'  => 'HTML/Code',
					),
					'default_value' => 'image',
				),
				array(
					'key'               => 'field_wp_ad_image',
					'label'             => 'Image',
					'name'              => 'wp_ad_image',
					'type'              => 'image',
					'return_format'     => 'url',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_type',
								'operator' => '==',
								'value'    => 'image',
							),
						),
					),
				),
				array(
					'key'               => 'field_wp_ad_destination_url',
					'label'             => 'Destination URL',
					'name'              => 'wp_ad_destination_url',
					'type'              => 'url',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_type',
								'operator' => '==',
								'value'    => 'image',
							),
						),
					),
				),
				array(
					'key'               => 'field_wp_ad_html_code',
					'label'             => 'HTML Code',
					'name'              => 'wp_ad_html_code',
					'type'              => 'textarea',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_type',
								'operator' => '==',
								'value'    => 'html',
							),
						),
					),
				),
				array(
					'key'           => 'field_wp_ad_weight',
					'label'         => 'Weight (1-10)',
					'name'          => 'wp_ad_weight',
					'type'          => 'number',
					'default_value' => 1,
					'min'           => 1,
					'max'           => 10,
				),
				array(
					'key'   => 'field_wp_ad_scheduling_heading',
					'label' => 'Scheduling & Limits',
					'type'  => 'accordion',
				),
				array(
					'key'   => 'field_wp_ad_start_date',
					'label' => 'Start Date',
					'name'  => 'wp_ad_start_date',
					'type'  => 'date_time_picker',
					'display_format' => 'Y-m-d H:i:s',
					'return_format'  => 'Y-m-d H:i:s',
				),
				array(
					'key'   => 'field_wp_ad_end_date',
					'label' => 'End Date',
					'name'  => 'wp_ad_end_date',
					'type'  => 'date_time_picker',
					'display_format' => 'Y-m-d H:i:s',
					'return_format'  => 'Y-m-d H:i:s',
				),
				array(
					'key'   => 'field_wp_ad_limit_impressions',
					'label' => 'Impression Limit',
					'name'  => 'wp_ad_limit_impressions',
					'type'  => 'number',
					'instructions' => 'Set to 0 or leave empty for no limit.',
				),
				array(
					'key'   => 'field_wp_ad_limit_clicks',
					'label' => 'Click Limit',
					'name'  => 'wp_ad_limit_clicks',
					'type'  => 'number',
					'instructions' => 'Set to 0 or leave empty for no limit.',
				),
				array(
					'key'   => 'field_wp_ad_geo_heading',
					'label' => 'Geo-Targeting',
					'type'  => 'accordion',
				),
				array(
					'key'           => 'field_wp_ad_geo_enabled',
					'label'         => 'Enable Geo-Targeting',
					'name'          => 'wp_ad_geo_enabled',
					'type'          => 'true_false',
					'ui'            => 1,
					'default_value' => 0,
				),
				array(
					'key'               => 'field_wp_ad_geo_mode',
					'label'             => 'Geo Mode',
					'name'              => 'wp_ad_geo_mode',
					'type'              => 'select',
					'choices'           => array(
						'include' => 'Include selected countries',
						'exclude' => 'Exclude selected countries',
					),
					'default_value'     => 'include',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_geo_enabled',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
				),
				array(
					'key'               => 'field_wp_ad_geo_countries',
					'label'             => 'Target Countries',
					'name'              => 'wp_ad_geo_countries',
					'type'              => 'select',
					'choices'           => self::get_country_choices(),
					'multiple'          => 1,
					'ui'                => 1,
					'ajax'              => 1,
					'placeholder'       => 'Select countries...',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_geo_enabled',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
				),
				array(
					'key'   => 'field_wp_ad_device_heading',
					'label' => 'Device Targeting',
					'type'  => 'accordion',
				),
				array(
					'key'           => 'field_wp_ad_device_enabled',
					'label'         => 'Enable Device Targeting',
					'name'          => 'wp_ad_device_enabled',
					'type'          => 'true_false',
					'ui'            => 1,
					'default_value' => 0,
				),
				array(
					'key'               => 'field_wp_ad_device_types',
					'label'             => 'Target Devices',
					'name'              => 'wp_ad_device_types',
					'type'              => 'checkbox',
					'choices'           => array(
						'mobile'  => 'Mobile',
						'tablet'  => 'Tablet',
						'desktop' => 'Desktop',
					),
					'layout'            => 'horizontal',
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_wp_ad_device_enabled',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'wp_ad',
					),
				),
			),
		) );

		acf_add_local_field_group( array(
			'key'      => 'group_wp_ad_zone_details',
			'title'    => 'Zone Details',
			'fields'   => array(
				array(
					'key'   => 'field_wp_ad_zone_dimensions',
					'label' => 'Zone Dimensions',
					'name'  => 'wp_ad_zone_dimensions',
					'type'  => 'text',
					'instructions' => 'e.g., 728x90, 300x250. This is for reference and can be used in your theme.',
					'placeholder'  => 'Width x Height',
				),
				array(
					'key'   => 'field_wp_ad_zone_description',
					'label' => 'Zone Description',
					'name'  => 'wp_ad_zone_description',
					'type'  => 'textarea',
					'rows'  => 3,
				),
			),
			'location' => array(
				array(
					array(
						'param'    => 'taxonomy',
						'operator' => '==',
						'value'    => 'ad_zone',
					),
				),
			),
		) );

		acf_add_local_field_group( array(
			'key'      => 'group_wp_ad_access_settings',
			'title'    => 'Access Settings',
			'fields'   => array(
				array(
					'key'           => 'field_wp_adserver_allowed_users_list',
					'label'         => 'Allowed Users',
					'name'          => 'wp_adserver_allowed_users_list',
					'type'          => 'user',
					'instructions'  => 'Select specific users who are allowed to manage advertisements.',
					'required'      => 0,
					'return_format' => 'id',
					'multiple'      => 1,
					'allow_null'    => 1,
					'ui'            => 1,
				),
			),
			'location' => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'wp-adserver-access',
					),
				),
			),
		) );
	}

	/**
	 * Returns an array of country choices (ISO alpha-2 => Country Name).
	 */
	public static function get_country_choices() {
		return array(
			'AF' => 'Afghanistan',
			'AX' => 'Aland Islands',
			'AL' => 'Albania',
			'DZ' => 'Algeria',
			'AS' => 'American Samoa',
			'AD' => 'Andorra',
			'AO' => 'Angola',
			'AI' => 'Anguilla',
			'AQ' => 'Antarctica',
			'AG' => 'Antigua and Barbuda',
			'AR' => 'Argentina',
			'AM' => 'Armenia',
			'AW' => 'Aruba',
			'AU' => 'Australia',
			'AT' => 'Austria',
			'AZ' => 'Azerbaijan',
			'BS' => 'Bahamas',
			'BH' => 'Bahrain',
			'BD' => 'Bangladesh',
			'BB' => 'Barbados',
			'BY' => 'Belarus',
			'BE' => 'Belgium',
			'BZ' => 'Belize',
			'BJ' => 'Benin',
			'BM' => 'Bermuda',
			'BT' => 'Bhutan',
			'BO' => 'Bolivia',
			'BA' => 'Bosnia and Herzegovina',
			'BW' => 'Botswana',
			'BV' => 'Bouvet Island',
			'BR' => 'Brazil',
			'IO' => 'British Indian Ocean Territory',
			'BN' => 'Brunei Darussalam',
			'BG' => 'Bulgaria',
			'BF' => 'Burkina Faso',
			'BI' => 'Burundi',
			'KH' => 'Cambodia',
			'CM' => 'Cameroon',
			'CA' => 'Canada',
			'CV' => 'Cape Verde',
			'KY' => 'Cayman Islands',
			'CF' => 'Central African Republic',
			'TD' => 'Chad',
			'CL' => 'Chile',
			'CN' => 'China',
			'CX' => 'Christmas Island',
			'CC' => 'Cocos (Keeling) Islands',
			'CO' => 'Colombia',
			'KM' => 'Comoros',
			'CG' => 'Congo',
			'CD' => 'Congo, Democratic Republic of the',
			'CK' => 'Cook Islands',
			'CR' => 'Costa Rica',
			'CI' => 'Côte d\'Ivoire',
			'HR' => 'Croatia',
			'CU' => 'Cuba',
			'CW' => 'Curaçao',
			'CY' => 'Cyprus',
			'CZ' => 'Czech Republic',
			'DK' => 'Denmark',
			'DJ' => 'Djibouti',
			'DM' => 'Dominica',
			'DO' => 'Dominican Republic',
			'EC' => 'Ecuador',
			'EG' => 'Egypt',
			'SV' => 'El Salvador',
			'GQ' => 'Equatorial Guinea',
			'ER' => 'Eritrea',
			'EE' => 'Estonia',
			'ET' => 'Ethiopia',
			'FK' => 'Falkland Islands (Malvinas)',
			'FO' => 'Faroe Islands',
			'FJ' => 'Fiji',
			'FI' => 'Finland',
			'FR' => 'France',
			'GF' => 'French Guiana',
			'PF' => 'French Polynesia',
			'TF' => 'French Southern Territories',
			'GA' => 'Gabon',
			'GM' => 'Gambia',
			'GE' => 'Georgia',
			'DE' => 'Germany',
			'GH' => 'Ghana',
			'GI' => 'Gibraltar',
			'GR' => 'Greece',
			'GL' => 'Greenland',
			'GD' => 'Grenada',
			'GP' => 'Guadeloupe',
			'GU' => 'Guam',
			'GT' => 'Guatemala',
			'GG' => 'Guernsey',
			'GN' => 'Guinea',
			'GW' => 'Guinea-Bissau',
			'GY' => 'Guyana',
			'HT' => 'Haiti',
			'HM' => 'Heard Island and McDonald Islands',
			'VA' => 'Holy See (Vatican City State)',
			'HN' => 'Honduras',
			'HK' => 'Hong Kong',
			'HU' => 'Hungary',
			'IS' => 'Iceland',
			'IN' => 'India',
			'ID' => 'Indonesia',
			'IR' => 'Iran',
			'IQ' => 'Iraq',
			'IE' => 'Ireland',
			'IM' => 'Isle of Man',
			'IL' => 'Israel',
			'IT' => 'Italy',
			'JM' => 'Jamaica',
			'JP' => 'Japan',
			'JE' => 'Jersey',
			'JO' => 'Jordan',
			'KZ' => 'Kazakhstan',
			'KE' => 'Kenya',
			'KI' => 'Kiribati',
			'KP' => 'Korea, Democratic People\'s Republic of',
			'KR' => 'Korea, Republic of',
			'KW' => 'Kuwait',
			'KG' => 'Kyrgyzstan',
			'LA' => 'Lao People\'s Democratic Republic',
			'LV' => 'Latvia',
			'LB' => 'Lebanon',
			'LS' => 'Lesotho',
			'LR' => 'Liberia',
			'LY' => 'Libya',
			'LI' => 'Liechtenstein',
			'LT' => 'Lithuania',
			'LU' => 'Luxembourg',
			'MO' => 'Macao',
			'MK' => 'Macedonia',
			'MG' => 'Madagascar',
			'MW' => 'Malawi',
			'MY' => 'Malaysia',
			'MV' => 'Maldives',
			'ML' => 'Mali',
			'MT' => 'Malta',
			'MH' => 'Marshall Islands',
			'MQ' => 'Martinique',
			'MR' => 'Mauritania',
			'MU' => 'Mauritius',
			'YT' => 'Mayotte',
			'MX' => 'Mexico',
			'FM' => 'Micronesia',
			'MD' => 'Moldova',
			'MC' => 'Monaco',
			'MN' => 'Mongolia',
			'ME' => 'Montenegro',
			'MS' => 'Montserrat',
			'MA' => 'Morocco',
			'MZ' => 'Mozambique',
			'MM' => 'Myanmar',
			'NA' => 'Namibia',
			'NR' => 'Nauru',
			'NP' => 'Nepal',
			'NL' => 'Netherlands',
			'NC' => 'New Caledonia',
			'NZ' => 'New Zealand',
			'NI' => 'Nicaragua',
			'NE' => 'Niger',
			'NG' => 'Nigeria',
			'NU' => 'Niue',
			'NF' => 'Norfolk Island',
			'MP' => 'Northern Mariana Islands',
			'NO' => 'Norway',
			'OM' => 'Oman',
			'PK' => 'Pakistan',
			'PW' => 'Palau',
			'PS' => 'Palestine',
			'PA' => 'Panama',
			'PG' => 'Papua New Guinea',
			'PY' => 'Paraguay',
			'PE' => 'Peru',
			'PH' => 'Philippines',
			'PN' => 'Pitcairn',
			'PL' => 'Poland',
			'PT' => 'Portugal',
			'PR' => 'Puerto Rico',
			'QA' => 'Qatar',
			'RE' => 'Réunion',
			'RO' => 'Romania',
			'RU' => 'Russian Federation',
			'RW' => 'Rwanda',
			'BL' => 'Saint Barthélemy',
			'SH' => 'Saint Helena',
			'KN' => 'Saint Kitts and Nevis',
			'LC' => 'Saint Lucia',
			'MF' => 'Saint Martin (French part)',
			'PM' => 'Saint Pierre and Miquelon',
			'VC' => 'Saint Vincent and the Grenadines',
			'WS' => 'Samoa',
			'SM' => 'San Marino',
			'ST' => 'Sao Tome and Principe',
			'SA' => 'Saudi Arabia',
			'SN' => 'Senegal',
			'RS' => 'Serbia',
			'SC' => 'Seychelles',
			'SL' => 'Sierra Leone',
			'SG' => 'Singapore',
			'SX' => 'Sint Maarten (Dutch part)',
			'SK' => 'Slovakia',
			'SI' => 'Slovenia',
			'SB' => 'Solomon Islands',
			'SO' => 'Somalia',
			'ZA' => 'South Africa',
			'GS' => 'South Georgia and the South Sandwich Islands',
			'SS' => 'South Sudan',
			'ES' => 'Spain',
			'LK' => 'Sri Lanka',
			'SD' => 'Sudan',
			'SR' => 'Suriname',
			'SJ' => 'Svalbard and Jan Mayen',
			'SZ' => 'Swaziland',
			'SE' => 'Sweden',
			'CH' => 'Switzerland',
			'SY' => 'Syrian Arab Republic',
			'TW' => 'Taiwan',
			'TJ' => 'Tajikistan',
			'TZ' => 'Tanzania',
			'TH' => 'Thailand',
			'TL' => 'Timor-Leste',
			'TG' => 'Togo',
			'TK' => 'Tokelau',
			'TO' => 'Tonga',
			'TT' => 'Trinidad and Tobago',
			'TN' => 'Tunisia',
			'TR' => 'Turkey',
			'TM' => 'Turkmenistan',
			'TC' => 'Turks and Caicos Islands',
			'TV' => 'Tuvalu',
			'UG' => 'Uganda',
			'UA' => 'Ukraine',
			'AE' => 'United Arab Emirates',
			'GB' => 'United Kingdom',
			'US' => 'United States',
			'UM' => 'United States Minor Outlying Islands',
			'UY' => 'Uruguay',
			'UZ' => 'Uzbekistan',
			'VU' => 'Vanuatu',
			'VE' => 'Venezuela',
			'VN' => 'Viet Nam',
			'VG' => 'Virgin Islands, British',
			'VI' => 'Virgin Islands, U.S.',
			'WF' => 'Wallis and Futuna',
			'EH' => 'Western Sahara',
			'YE' => 'Yemen',
			'ZM' => 'Zambia',
			'ZW' => 'Zimbabwe',
		);
	}
}
